In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("Data.csv")

In [5]:
df

,Shipment_ID,Parent_Shipment_ID,Order_Status,Tracking_ID,Parcel_ID,Parcel_Count,Carrier,Service_Level,Scan_Source,Event_TS,...,Exception_Reason,Declared_Value,Freight_Cost,Surcharge,COD_Amount,Claim_Amount,Currency,Customer_Name,Customer_Phone,Street_Address
0,SHP-10001,NaN,ACTIVE,trk-9001,PCL-9001,1,FastShip,Exp,DRIVER_APP,2026-07-12 09:00 +05:30,...,NaN,2500.00,120.00,15.0,500.0000,0,INR,Ramesh Mohanty,+91-9861012345,"Plot 42, Saheed Nagar, Bhubaneswar"
1,SHP-10001,NaN,ACTIVE,TRK-9001,PCL-9001,1,FAST SHIP,EXPRESS,HUB_SCANNER,2026-07-12T03:30:00Z,...,NaN,2500.00,120.00,15.0,500.0000,0,INR,Ramesh Mohanty,9861012345,"Plot 42, Saheed Nagar, Bhubaneswar"
2,SHP-10002,NaN,ACTIVE,TRK-9002,PCL-9002,1,RoadX,Std,DRIVER_APP,2026-07-13 08:00,...,NaN,1800.00,0.00,0.0,0.0000,0,INR,Sujata Das,9437054321,"Link Road, Near Nishamani Hall, Cuttack"
3,SHP-10003,NaN,ACTIVE,TRK-9003,PCL-9003,2,Road-X,STANDARD,HUB_SCANNER,2026-07-13T10:00:00Z,...,Damaged,1200.00,210.00,25.0,1200.0000,1200,INR,Bikash Jena,8249011223,"Buxi Bazar, Main Road, Cuttack"
4,SHP-10004,SHP-09950,RETURN_RTS,TRK-9002,PCL-9004,1,Fast-Ship,EXPRESS,DRIVER_APP,2026-07-11T04:00:00Z,...,Recipient Unavailable,3200.00,150.00,0.0,0.0000,0,INR,Anita Patra,7008122334,"Kalpana Square, Laxmisagar, BBSR"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,SHP-11915,NaN,ACTIVE,TRK-11915,PCL-11915,1,Odisha-Exp,Next-Day,API_WEBHOOK,2026-07-10 10:54 +05:30,...,NaN,8531.66,209.81,25.0,450.0000,0,INR,Manas Bhoi,07110896587,"Plot 42, Saheed Nagar, Bhubaneswar"
9996,SHP-11915,NaN,ACTIVE,TRK-11915,PCL-11915,1,FastShip,Next-Day,HUB_SCANNER,2026-07-10T12:51:00Z,...,NaN,8531.66,209.81,25.0,450.0000,0,NaN,Manas Bhoi,07110896587,"Plot 42, Saheed Nagar, Bhubaneswar"
9997,SHP-11915,NaN,ACTIVE,TRK-11915,PCL-11915,1,Odisha-Exp,Next-Day,DRIVER_APP,2026-07-11 00:04 +05:30,...,NaN,8531.66,0.00,25.0,0.4500,0,INR,Manas Bhoi,07110896587,"Plot 42, Saheed Nagar, Bhubaneswar"
9998,TEST-11916,NaN,TEST_ORDER,TRK-11916,PCL-11916,0,OdishaExpress,EXPRESS,DRIVER_APP,2026-07-23 10:43 +05:30,...,NaN,4732.47,0.00,50.0,2499.0000,0,INR,NaN,9069150103,"Fakir Mohan Golai, Station Road, Balasore"
9999,TEST-11916,NaN,TEST_ORDER,TRK-11916,PCL-11916,0,OdishaExpress,EXPRESS,MANUAL_ENTRY,2026-07-24 00:09 +05:30,...,NaN,4732.47,0.00,50.0,0.2499,0,INR,NaN,9069150103,"Fakir Mohan Golai, Station Road, Balasore"

In [7]:
df.head()

,Shipment_ID,Parent_Shipment_ID,Order_Status,Tracking_ID,Parcel_ID,Parcel_Count,Carrier,Service_Level,Scan_Source,Event_TS,...,Exception_Reason,Declared_Value,Freight_Cost,Surcharge,COD_Amount,Claim_Amount,Currency,Customer_Name,Customer_Phone,Street_Address
0,SHP-10001,NaN,ACTIVE,trk-9001,PCL-9001,1,FastShip,Exp,DRIVER_APP,2026-07-12 09:00 +05:30,...,NaN,2500.0,120.0,15.0,500.0,0,INR,Ramesh Mohanty,+91-9861012345,"Plot 42, Saheed Nagar, Bhubaneswar"
1,SHP-10001,NaN,ACTIVE,TRK-9001,PCL-9001,1,FAST SHIP,EXPRESS,HUB_SCANNER,2026-07-12T03:30:00Z,...,NaN,2500.0,120.0,15.0,500.0,0,INR,Ramesh Mohanty,9861012345,"Plot 42, Saheed Nagar, Bhubaneswar"
2,SHP-10002,NaN,ACTIVE,TRK-9002,PCL-9002,1,RoadX,Std,DRIVER_APP,2026-07-13 08:00,...,NaN,1800.0,0.0,0.0,0.0,0,INR,Sujata Das,9437054321,"Link Road, Near Nishamani Hall, Cuttack"
3,SHP-10003,NaN,ACTIVE,TRK-9003,PCL-9003,2,Road-X,STANDARD,HUB_SCANNER,2026-07-13T10:00:00Z,...,Damaged,1200.0,210.0,25.0,1200.0,1200,INR,Bikash Jena,8249011223,"Buxi Bazar, Main Road, Cuttack"
4,SHP-10004,SHP-09950,RETURN_RTS,TRK-9002,PCL-9004,1,Fast-Ship,EXPRESS,DRIVER_APP,2026-07-11T04:00:00Z,...,Recipient Unavailable,3200.0,150.0,0.0,0.0,0,INR,Anita Patra,7008122334,"Kalpana Square, Laxmisagar, BBSR"

In [9]:
df.shape

(10000, 35)

In [10]:
df.columns

Index(['Shipment_ID', 'Parent_Shipment_ID', 'Order_Status', 'Tracking_ID',
       'Parcel_ID', 'Parcel_Count', 'Carrier', 'Service_Level', 'Scan_Source',
       'Event_TS', 'Promised_Delivery_TS', 'Event_Code', 'Status',
       'Origin_Depot', 'Destination_Zone', 'Country_Code', 'Route_ID',
       'Stop_Seq', 'GPS_Coords', 'Weight', 'Weight_Unit', 'Dimensions_L_W_H',
       'Dim_Unit', 'Attempt_No', 'POD_ID', 'Exception_Reason',
       'Declared_Value', 'Freight_Cost', 'Surcharge', 'COD_Amount',
       'Claim_Amount', 'Currency', 'Customer_Name', 'Customer_Phone',
       'Street_Address'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 35 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Shipment_ID           10000 non-null  object
 1   Parent_Shipment_ID    374 non-null    object
 2   Order_Status          10000 non-null  object
 3   Tracking_ID           10000 non-null  object
 4   Parcel_ID             10000 non-null  object
 5   Parcel_Count          10000 non-null  int64
 6   Carrier               10000 non-null  object
 7   Service_Level         10000 non-null  object
 8   Scan_Source           10000 non-null  object
 9   Event_TS              9825 non-null   object
 10  Promised_Delivery_TS  9661 non-null   object
 11  Event_Code            10000 non-null  object
 12  Status                10000 non-null  object
 13  Origin_Depot          10000 non-null  object
 14  Destination_Zone      10000 non-null  object
 15  Country_Code          8389 non-null   object
 16  Route_ID              10000 non-null  object
 17  Stop_Seq              10000 non-null  int64
 18  GPS_Coords            9161 non-null   object
 19  Weight                9721 non-null   float64
 20  Weight_Unit           10000 non-null  object
 21  Dimensions_L_W_H      9605 non-null   object
 22  Dim_Unit              10000 non-null  object
 23  Attempt_No            10000 non-null  int64
 24  POD_ID                1678 non-null   object
 25  Exception_Reason      280 non-null    object
 26  Declared_Value        10000 non-null  float64
 27  Freight_Cost          10000 non-null  float64
 28  Surcharge             7990 non-null   float64
 29  COD_Amount            10000 non-null  float64
 30  Claim_Amount          10000 non-null  int64
 31  Currency              9796 non-null   object
 32  Customer_Name         9665 non-null   object
 33  Customer_Phone        9502 non-null   object
 34  Street_Address        9678 non-null   object
dtypes: float64(5), int64(4), object(26)
memory usage: 2.7+ MB

In [12]:
df.isnull().sum()

Shipment_ID                0
Parent_Shipment_ID      9626
Order_Status               0
Tracking_ID                0
Parcel_ID                  0
Parcel_Count               0
Carrier                    0
Service_Level              0
Scan_Source                0
Event_TS                 175
Promised_Delivery_TS     339
Event_Code                 0
Status                     0
Origin_Depot               0
Destination_Zone           0
Country_Code            1611
Route_ID                   0
Stop_Seq                   0
GPS_Coords               839
Weight                   279
Weight_Unit                0
Dimensions_L_W_H         395
Dim_Unit                   0
Attempt_No                 0
POD_ID                  8322
Exception_Reason        9720
Declared_Value             0
Freight_Cost               0
Surcharge               2010
COD_Amount                 0
Claim_Amount               0
Currency                 204
Customer_Name            335
Customer_Phone           498
Street_Address           322
dtype: int64

In [13]:
df.duplicated().sum()

32

In [14]:
df.describe(include='all')

,Shipment_ID,Parent_Shipment_ID,Order_Status,Tracking_ID,Parcel_ID,Parcel_Count,Carrier,Service_Level,Scan_Source,Event_TS,...,Exception_Reason,Declared_Value,Freight_Cost,Surcharge,COD_Amount,Claim_Amount,Currency,Customer_Name,Customer_Phone,Street_Address
count,10000,374,10000,10000,10000,10000.000000,10000,10000,10000,9825,...,280,10000.000000,10000.000000,7990.000000,10000.000000,10000.000000,9796,9665,9502,9678
unique,2359,53,5,3182,1916,NaN,14,11,4,8965,...,12,NaN,NaN,NaN,NaN,NaN,3,801,1821,16
top,SHP-10236,SHP-INVALID-999,ACTIVE,TRK-11729,PCL-10507,NaN,Blue-Jet,Surface,HUB_SCANNER,2026-07-20T10:34:00Z,...,Incomplete Address,NaN,NaN,NaN,NaN,NaN,INR,Deepak Panda,07147341153,"Kalpana Square, Laxmisagar, BBSR"
freq,8,97,9339,12,8,NaN,783,987,2823,4,...,35,NaN,NaN,NaN,NaN,NaN,8460,38,8,705
mean,NaN,NaN,NaN,NaN,NaN,1.105700,NaN,NaN,NaN,NaN,...,NaN,7158.090504,180.927089,22.032541,646.235406,2.100000,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,0.524743,NaN,NaN,NaN,NaN,...,NaN,4477.416061,148.357063,17.797387,830.730002,43.425552,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,-1.000000,NaN,NaN,NaN,NaN,...,NaN,-500.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,NaN,3336.737500,0.000000,15.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,NaN,7130.470000,176.455000,15.000000,450.000000,0.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,NaN,11022.940000,308.630000,25.000000,899.000000,0.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,...,NaN,14983.900000,449.500000,50.000000,2499.000000,1200.000000,NaN,NaN,NaN,NaN